// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // Fallback to iOS for macOS as a temporary measure
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkkMtp-S32Sgz8wbH7Tmo7RE82IdUwP90',
    appId: '1:927257142657:web:4c4ce6e334ac7668717480', // Sanket: Updated to match project number, needs verification from Firebase Console
    messagingSenderId: '927257142657',
    projectId: 'swayamvar-e2a6d',
    authDomain: 'swayamvar-e2a6d.firebaseapp.com',
    storageBucket: 'swayamvar-e2a6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkkMtp-S32Sgz8wbH7Tmo7RE82IdUwP90',
    appId: '1:927257142657:android:4c4ce6e334ac7668717480',
    messagingSenderId: '927257142657',
    projectId: 'swayamvar-e2a6d',
    storageBucket: 'swayamvar-e2a6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkkMtp-S32Sgz8wbH7Tmo7RE82IdUwP90',
    appId: '1:927257142657:ios:4c4ce6e334ac7668717480', // Sanket: Updated to match project number, needs verification from Firebase Console
    messagingSenderId: '927257142657',
    projectId: 'swayamvar-e2a6d',
    storageBucket: 'swayamvar-e2a6d.firebasestorage.app',
    iosBundleId:
        'com.activeitzone.active_matrimonial_flutter_app.active_matrimonial_flutter_app',
  );
}
