// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // Fallback to iOS for macOS as a temporary measure
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vwo1U5DTOu3XOQLxBuly8c_Wvz07fM4',
    appId: '1:546131385866:web:783f30cf04a4e0baaf986c', // Guessed web ID based on pattern, but focusing on Android
    messagingSenderId: '546131385866',
    projectId: 'matri-24e1f',
    authDomain: 'matri-24e1f.firebaseapp.com',
    storageBucket: 'matri-24e1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_vwo1U5DTOu3XOQLxBuly8c_Wvz07fM4',
    appId: '1:546131385866:android:6a322f568dee5d13f189f3',
    messagingSenderId: '546131385866',
    projectId: 'matri-24e1f',
    storageBucket: 'matri-24e1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vwo1U5DTOu3XOQLxBuly8c_Wvz07fM4',
    appId: '1:546131385866:ios:c6a14d063ab8ed51af986c', // Guessed iOS ID, but focussing on Android
    messagingSenderId: '546131385866',
    projectId: 'matri-24e1f',
    storageBucket: 'matri-24e1f.appspot.com',
    iosBundleId: 'com.activeitzone.active_matrimonial_flutter_app.active_matrimonial_flutter_app',
  );
}
